services:
  database:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - 'psql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=smoothie

volumes:
  psql-data:
